import { motion, useReducedMotion } from 'framer-motion'
import { FileLock2, Radio, ShieldCheck } from 'lucide-react'
import { PageHero } from '../components/shared/PageHero'

const sections = [
  ['information', 'Information we handle', 'SportZoneBD handles information needed to operate accounts, premium access, payments, notifications, and the streaming experience. This may include account details such as your email address and profile information, authentication and session information, subscription status, and payment records submitted through the application.\n\nWhen you submit a manual payment, the transaction identifier and selected plan are stored with the payment request so it can be reviewed. Do not submit passwords, card numbers, or other information that the payment form does not request.'],
  ['use', 'How information is used', 'Information is used to authenticate users, maintain accounts, process and review subscription requests, determine premium access, deliver notifications, protect the service, and respond to support or report requests.\n\nTechnical playback events may be processed to understand stream starts, buffering, errors, and player health. This telemetry is used for service operation and troubleshooting rather than as a promise of uninterrupted playback.'],
  ['streaming-ads', 'Streaming and advertising', 'SportZoneBD presents channels, matches, events, and highlights through the player. Some playback sources are supplied through external media URLs and may be unavailable, changed, or subject to the rights and policies of the source provider. The application does not represent that it owns every stream or piece of media presented through the service.\n\nSome channel or match access may use an interstitial advertisement session. When you choose to watch an advertisement, the service records the session needed to enforce its configured duration and unlock period. Returning before the required duration can cancel the session; completing it can grant the configured temporary access period.'],
  ['storage', 'Cookies and browser storage', 'The application uses browser storage for selected product functions, including authentication persistence when you choose to remain signed in, favorites, recent items, theme preferences, and temporary navigation or advertisement state. Authentication and advertisement sessions may also use server-managed cookies needed to validate requests.\n\nYou can clear browser storage or change browser settings, but doing so may sign you out, remove local favorites or preferences, or require an advertisement flow to start again.'],
  ['sharing-security', 'Sharing, retention, and security', 'Information may be processed by service providers that help operate authentication, media delivery, application hosting, notifications, analytics, or payment review. SportZoneBD does not sell personal information as part of the features audited for this policy. External links, streams, and providers have their own terms and privacy practices.\n\nWe retain account, subscription, payment-review, notification, and operational records for as long as needed to provide the service, administer access, resolve disputes, meet operational needs, or comply with applicable requirements. No online service can guarantee absolute security.'],
  ['choices', 'Your choices and questions', 'You may manage notification preferences in account settings where available, clear local browser data, stop using a stream or advertisement flow, and contact SportZoneBD through the support or report mechanisms provided in the application. Account and payment records may require verification before changes are made.\n\nThis policy may be updated when the service or its data practices change. Because the project does not expose a configured legal entity address or dedicated privacy email in its public configuration, use the existing in-app support or report path for privacy questions.'],
] as const

export default function PrivacyPolicyPage() {
  const reducedMotion = useReducedMotion()
  return <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="app-page relative min-h-[calc(100vh-9rem)] w-full min-w-0 space-y-3 overflow-hidden px-4 pb-28 sm:space-y-3 sm:px-6 lg:px-8 xl:pb-8">
    <div className="pointer-events-none absolute -right-20 top-12 text-(--accent)/4" aria-hidden="true"><Radio className="h-64 w-64" /></div>
    <PageHero title="Privacy Policy" description="How SportZoneBD handles account, subscription, payment-review, streaming, notification, and service-operation information." eyebrow="Trust & privacy" icon={ShieldCheck} className="border-(--accent)/20 bg-linear-to-br from-(--surface-strong) via-(--surface) to-(--accent)/10 shadow-[0_30px_90px_rgba(2,6,23,0.28)]" />
    <div className="relative mx-auto grid w-full max-w-7xl gap-5 lg:gap-8">
      <nav aria-label="Privacy Policy sections" className="w-full min-w-0 rounded-2xl border border-(--border) bg-(--surface-soft)/60 p-2 shadow-[0_18px_50px_var(--shadow)] backdrop-blur-xl lg:p-3"><p className="px-3 pb-2 pt-1 text-[10px] font-bold uppercase tracking-[0.2em] text-(--text-muted)">On this page</p><div className="no-scrollbar flex flex-nowrap gap-1 overflow-x-auto lg:flex-wrap lg:overflow-visible">{sections.map(([id, title], index) => <a key={id} href={`#${id}`} className="flex shrink-0 items-center gap-2 whitespace-nowrap rounded-xl px-3 py-2 text-sm text-(--text-muted) transition duration-200 hover:bg-white/10 hover:text-(--text-primary) focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--accent)"><span className="text-[10px] font-bold text-(--accent)">{String(index + 1).padStart(2, '0')}</span>{title}</a>)}</div></nav>
      <div className="mx-auto w-full max-w-5xl min-w-0 space-y-4">{sections.map(([id, title, body], index) => <motion.section key={id} id={id} initial={{ opacity: 0, y: reducedMotion ? 0 : 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-8% 0px' }} transition={{ duration: reducedMotion ? 0 : 0.3, delay: reducedMotion ? 0 : Math.min(index * 0.03, 0.15) }} className="group min-w-0 scroll-mt-24 wrap-break-word rounded-3xl border border-(--border) bg-(--surface-soft)/55 p-4 shadow-[0_18px_55px_var(--shadow)] backdrop-blur-xl transition duration-300 hover:-translate-y-0.5 hover:border-(--accent)/25 sm:p-7"><div className="mb-4 flex min-w-0 items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl border border-(--accent)/25 bg-(--accent)/10 text-xs font-bold text-(--accent)">{index + 1}</span><div className="flex min-w-0 items-center gap-3 pt-1"><FileLock2 className="h-5 w-5 shrink-0 text-(--accent)" aria-hidden="true" /><h2 className="wrap-break-word text-xl font-semibold text-(--text-primary) sm:text-2xl">{title}</h2></div></div><div className="space-y-3 wrap-break-word pl-0 text-sm leading-7 text-(--text-secondary) sm:pl-11 sm:text-base">{body.split('\n\n').map((paragraph) => <p key={paragraph} className="wrap-break-word">{paragraph}</p>)}</div></motion.section>)}</div>
    </div>
  </motion.main>
}
