import { motion, useReducedMotion } from 'framer-motion'
import { CircleCheck, FileText, Radio } from 'lucide-react'
import { PageHero } from '../components/shared/PageHero'

const sections = [
  ['acceptance', 'Acceptance and service scope', 'By using SportZoneBD, you agree to use the public website, accounts, channels, matches, events, highlights, subscriptions, notifications, and player features in accordance with these terms and applicable law.\n\nSportZoneBD is a sports-content and streaming interface. Features, schedules, channels, highlights, and streams may change or become unavailable without notice.'],
  ['accounts', 'Accounts and access', 'Some features can be viewed without an account. Account features require accurate information and appropriate protection of your sign-in details. Authentication persistence may be selected through the application’s sign-in flow.\n\nYou are responsible for activity carried out through your account. Contact SportZoneBD through the available support or report mechanisms if you believe account access has been misused.'],
  ['content', 'Sports content and streams', 'SportZoneBD may present live matches, channels, events, highlights, and other programming through sources that can include external streaming URLs. Availability, quality, timing, language, and continuity are not guaranteed.\n\nYou may not copy, redistribute, re-host, scrape, interfere with, or use the service to bypass access controls for content or streams. External sites and media sources are subject to their own terms. SportZoneBD does not claim ownership of content supplied by third parties.'],
  ['premium', 'Premium plans and manual payments', 'Premium plans, prices, durations, device limits, and benefits are shown in the application and may vary by plan. Premium access begins only after the relevant payment request has been reviewed and approved through the existing service process.\n\nThe current payment flow allows a user to select a plan and submit a transaction identifier for administrative review using the configured manual payment instructions. SportZoneBD does not represent that automatic payment verification is available. No refund, approval-time, or renewal promise is stated here because those rules are not defined in the application’s public configuration.'],
  ['ads-notifications', 'Advertisements and notifications', 'Some access flows may require an interstitial advertisement session. You must follow the displayed instructions and wait for the configured session duration. Leaving early can cancel the session and prevent access from being unlocked.\n\nIf enabled for your account, notifications may include in-app updates and service or match-related messages. You can manage available notification preferences in account settings.'],
  ['acceptable-use', 'Acceptable use and enforcement', 'Do not misuse the service, attempt unauthorized access, submit false payment information, disrupt playback or APIs, bypass premium or advertisement controls, infringe rights, distribute malicious content, or interfere with another user’s access.\n\nSportZoneBD may limit, suspend, or end access where necessary to protect users, the service, content providers, or payment-review processes.'],
  ['availability', 'Availability and changes', 'The service is provided as available. Playback, schedules, notifications, advertisements, and premium features can be affected by network conditions, source-provider changes, maintenance, or other factors outside the application’s control.\n\nWe may update features and these terms as the service develops. Continued use after an update means you are using the current version presented on this page.'],
] as const

export default function TermsOfServicePage() {
  const reducedMotion = useReducedMotion()
  return <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="app-page relative min-h-[calc(100vh-9rem)] w-full min-w-0 space-y-3 overflow-hidden px-4 pb-28 sm:space-y-3 sm:px-6 lg:px-8 xl:pb-8">
    <div className="pointer-events-none absolute -left-20 top-12 text-(--accent-secondary)/4" aria-hidden="true"><Radio className="h-64 w-64" /></div>
    <PageHero title="Terms of Service" description="The rules for using SportZoneBD accounts, sports content, streaming, advertisements, notifications, and premium access." eyebrow="Service terms" icon={FileText} className="border-(--accent-secondary)/20 bg-linear-to-br from-(--surface-strong) via-(--surface) to-(--accent-secondary)/10 shadow-[0_30px_90px_rgba(2,6,23,0.28)]" />
    <div className="relative mx-auto grid w-full max-w-7xl gap-5 lg:gap-8">
      <nav aria-label="Terms of Service sections" className="w-full min-w-0 rounded-2xl border border-(--border) bg-(--surface-soft)/60 p-2 shadow-[0_18px_50px_var(--shadow)] backdrop-blur-xl lg:p-3"><p className="px-3 pb-2 pt-1 text-[10px] font-bold uppercase tracking-[0.2em] text-(--text-muted)">On this page</p><div className="no-scrollbar flex flex-nowrap gap-1 overflow-x-auto lg:flex-wrap lg:overflow-visible">{sections.map(([id, title], index) => <a key={id} href={`#${id}`} className="flex shrink-0 items-center gap-2 whitespace-nowrap rounded-xl px-3 py-2 text-sm text-(--text-muted) transition duration-200 hover:bg-white/10 hover:text-(--text-primary) focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--accent)"><span className="text-[10px] font-bold text-(--accent)">{String(index + 1).padStart(2, '0')}</span>{title}</a>)}</div></nav>
      <div className="mx-auto w-full max-w-5xl min-w-0 space-y-4">{sections.map(([id, title, body], index) => <motion.section key={id} id={id} initial={{ opacity: 0, y: reducedMotion ? 0 : 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-8% 0px' }} transition={{ duration: reducedMotion ? 0 : 0.3, delay: reducedMotion ? 0 : Math.min(index * 0.03, 0.15) }} className="group min-w-0 scroll-mt-24 wrap-break-word rounded-3xl border border-(--border) bg-(--surface-soft)/55 p-4 shadow-[0_18px_55px_var(--shadow)] backdrop-blur-xl transition duration-300 hover:-translate-y-0.5 hover:border-(--accent)/25 sm:p-7"><div className="mb-4 flex min-w-0 items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl border border-(--accent)/25 bg-(--accent)/10 text-xs font-bold text-(--accent)">{index + 1}</span><div className="flex min-w-0 items-center gap-3 pt-1"><CircleCheck className="h-5 w-5 shrink-0 text-(--accent)" aria-hidden="true" /><h2 className="wrap-break-word text-xl font-semibold text-(--text-primary) sm:text-2xl">{title}</h2></div></div><div className="space-y-3 wrap-break-word pl-0 text-sm leading-7 text-(--text-secondary) sm:pl-11 sm:text-base">{body.split('\n\n').map((paragraph) => <p key={paragraph} className="wrap-break-word">{paragraph}</p>)}</div></motion.section>)}</div>
    </div>
  </motion.main>
}
